### ISSUE TITLE
Something went wrong when trying to book timeslot

### ISSUE THREAD

**Issue by dst6se** [kalkih/passport-appointment-bot#1]
Every time i find a timeslot this error appear 

[22:35:59] [error]      Something went wrong when trying to book timeslot
[22:35:59] [error]      Failed booking slot 2022-10-12 12:20:00

**Comment by xxandeer** [comment]
The problem is that "Uppgifter till bokningen" has different values in the Förnamn and Efternamn fields depending on wich region your searching in.

**Comment by dst6se** [comment]
Thanks for your help!
Customers[0].Services[0].ServiceId was different !

**Comment by kalkih** [comment]
Now fixed
