### ISSUE TITLE
Hi thank u for update!

### ISSUE THREAD

**Issue by jarpalmer1** [kalkih/passport-appointment-bot#13]
Thank u so much for ur update how do I download the new files? Do I need to download config file and bot again? Or how? I appreciate ur work so much, thank u!!!!

**Comment by kalkih** [comment]
New version is available [here (v3.0.0)](https://github.com/kalkih/passport-appointment-bot/releases/tag/v3.0.0), including a description of what has changed.

There where no changes made to the config in this release, so you can continue with your existing.

Let me know if you have further questions.

**Comment by jarpalmer1** [comment]
The bot just crash for me please help, thank u!
