### ISSUE TITLE
Automatic crash?

### ISSUE THREAD

**Issue by jarpalmer1** [kalkih/passport-appointment-bot#14]
I have fixed the config file and then when double press on the bot it opens but then crash directly.. What can my issue be? Thank u for ur update btw!!!!

**Comment by kalkih** [comment]
What Operating system, and what release file are yo running?
Can you send me the `.error.log` file?

**Comment by jarpalmer1** [comment]
Im not the best with computers, but thank u for ur time. So where Can I find this .error.log file in same folder it isnt.. thanks again!

**Comment by kalkih** [comment]
The `.error` file should be located in the same folder as you ran the program from yes, but it could be that the app crashes before it's created if you can't find it.

Try running the program as administrator, Right-click -> "Run as administrator".

Double check your configuration, compare with the one you can download from the release and make sure it looks correct, especially check the location of quotes and commas.

I just tried the latest release on a windows 10 machine and it worked as expected.

**Comment by nellieholland** [comment]
but it could be that the app crashes before it's created if you can't find it.
> 


Hi, I have same problem as u said I think it crashes before opening..

this is my congif file I have just changed the name but it is 4 person all with 2 last names {
  "region": "Stockholm",
  "locations": ["Flemingsberg", "Globen", "Haninge", "Järva", "Nacka", "Norrtälje", "Sollentuna, "Solna", "Sthlm City", "Södertälje", "Södra Roslagen"],
  "max_date": "2022-07-10",
  "email": "example@gmail.com",
  "phone": "0712345678",
  "firstname": ["Adam", "Bertil", "Åke", "Tor"],
  "lastname": ["Svensson Svensson", "Svensson Svensson", "Svensson Svenssson", "Svensson Svensson"],
  "passport": true,
  "id": false,
  "sessions": 1,
  "throttle": 0
}

**Comment by kalkih** [comment]
@nellieholland You're missing a " after sollentuna.

Here's the corrected config:
```json
{
  "region": "Stockholm",
  "locations": ["Flemingsberg", "Globen", "Haninge", "Järva", "Nacka", "Norrtälje", "Sollentuna", "Solna", "Sthlm City", "Södertälje", "Södra Roslagen"],
  "max_date": "2022-07-10",
  "email": "example@gmail.com",
  "phone": "0712345678",
  "firstname": ["Adam", "Bertil", "Åke", "Tor"],
  "lastname": ["Svensson Svensson", "Svensson Svensson", "Svensson Svenssson", "Svensson Svensson"],
  "passport": true,
  "id": false,
  "sessions": 1,
  "throttle": 0
}
```

Lycka till i sökandet!

**Comment by nellieholland** [comment]
"> Lycka till i sökandet!"


Tusen tusen tack!!!! Funkar så bra!! En sista fråga rekkomenderar du att ha 6 på aktiva sessions? Och vad ska man sätta som "throttle" för att få en tid så snabbt som möjlitgt.. :)

**Comment by kalkih** [comment]
Jag vet inte vad bästa konfigurationen är, jag skulle testat köra 4 sessions och 0.25 throttle, lite jobbigare med fler sessions nu när man måste lösa captchan själv men kan vara värt det.

Ju fler desto bättre egentligen sålänge man inte blir tillfälligt blockerad för att man gör för mycket requests, man blev inte det tidigare (kan dock ha ändrats).

**Comment by nellieholland** [comment]
> Jag vet inte vad bästa konfigurationen är, jag skulle testat köra 4 sessions och 0.25 throttle, lite jobbigare med fler sessions nu när man måste lösa captchan själv men kan vara värt det.
> 
> Ju fler desto bättre egentligen sålänge man inte blir tillfälligt blockerad för att man gör för mycket requests, man blev inte det tidigare (kan dock ha ändrats).

Den där 0.25 throttle vad betyder det egentligen? Har kört den i typ 10 min nu på 6 sessions utan att bli blockad men har 0 på throttle, och en gång till du är en riktig stjärna tusen miljoners tack för boten!!!!

**Comment by nellieholland** [comment]
Reached maximum redirect of 20 for URL: https://bokapass.nemoq.se/Booking/403.htm
      Cannot read properties of undefined (reading 'text')"
