### ISSUE TITLE
Failed opening captcha page Cannot read properties of undefined (reading 'pages')

### ISSUE THREAD

**Issue by Ireath** [kalkih/passport-appointment-bot#16]
Gettings this error after the update: 

{"level":"error","message":"Failed opening captcha page Cannot read properties of undefined (reading 'pages')","stack":"TypeError: Cannot read properties of undefined (reading 'pages')\n    at CaptchaService.openCaptcha (C:\\snapshot\\pass-bot\\src\\services\\captchaService.js:47:35)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async CaptchaService.getNewVerifiedToken (C:\\snapshot\\pass-bot\\src\\services\\captchaService.js:63:5)\n    at async BookingService.init (C:\\snapshot\\pass-bot\\src\\services\\bookingService.js:61:27)\n    at async init (C:\\snapshot\\pass-bot\\src\\index.js:68:3)\n    at async C:\\snapshot\\pass-bot\\src\\index.js:57:5","timestamp":"2022-04-02T19:10:17.206Z"}
{"level":"error","message":"Failed opening captcha page Cannot read properties of undefined (reading 'pages')","stack":"TypeError: Cannot read properties of undefined (reading 'pages')\n    at CaptchaService.openCaptcha (C:\\snapshot\\pass-bot\\src\\services\\captchaService.js:47:35)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async CaptchaService.getNewVerifiedToken (C:\\snapshot\\pass-bot\\src\\services\\captchaService.js:63:5)\n    at async BookingService.init (C:\\snapshot\\pass-bot\\src\\services\\bookingService.js:61:27)\n    at async init (C:\\snapshot\\pass-bot\\src\\index.js:68:3)\n    at async C:\\snapshot\\pass-bot\\src\\index.js:57:5","timestamp":"2022-04-02T19:10:42.704Z"}

**Comment by kalkih** [comment]
@Ireath Did you find a solution? interested in what it was

**Comment by Ireath** [comment]
I tried it on my computer at work but I guess some network settings blocked a port or something. Runs perfectly on my home setup.
