### ISSUE TITLE
Sound notification when time is found?

### ISSUE THREAD

**Issue by svenbox** [kalkih/passport-appointment-bot#17]
Now when there is a need for another captcha to book a time, is it possible to add a notification sound alert when that's needed? 
Thanks for great work!

**Comment by pilotniq** [comment]
Using a service like [Pushover](https://pushover.net/) to send a push notification to your phone would also be a nice way to be notified.

**Comment by kalkih** [comment]
Notification sound when captcha is needed was added with the latest release.
