### ISSUE TITLE
New error on recaptcha

### ISSUE THREAD

**Issue by kedase** [kalkih/passport-appointment-bot#18]
Getting redirected to "https://reserv.polisen.se/for-manga-anrop/"
have tried to get pass this with vpn on computer, different computer and different network but always stops on that page.
Any smart ideas to get pass this?

**Comment by kalkih** [comment]
Fixed with https://github.com/kalkih/passport-appointment-bot/commit/c5b8c80ccac664c2d48d1a7758da1cf9c3656102

New url for the captcha, let's hope this one lasts longer

**Comment by kedase** [comment]
Fixed 1st captcha, but when second captcha when found a time came, same problem again, https://reserv.polisen.se/for-manga-anrop/
so could not make booking.

By the way, ur a king ;-)

**Comment by kalkih** [comment]
@kedase Thanks, that should be fixed in the latest release! #20
