### ISSUE TITLE
This website is not within the supported domains for this Sitekey (Error 1415)

### ISSUE THREAD

**Issue by karlsso** [kalkih/passport-appointment-bot#19]
When starting passport-appointment-bot-win-x64 the captcha opens up but shows "This website is not within the supported domains for this Sitekey (Error 1415)".
![129644757b900febfbd8ec4269cc1dbf](https://user-images.githubusercontent.com/102900562/161421276-27d7ab63-24c6-415c-bc0b-40e24fc284e0.png)

**Comment by kalkih** [comment]
This should have been fixed, see #15
Are you running the latest version of the bot?
