### ISSUE TITLE
Second captcha not working

### ISSUE THREAD

**Issue by karlsso** [kalkih/passport-appointment-bot#20]
The first captcha works now perfectly but when I found a time and the second captcha should be there it redirected me to "https://reserv.polisen.se/for-manga-anrop/" and therefore could not make the booking.

**Comment by robiot** [comment]
Ah they started ip blocking now. Well then you probably need to cycle through proxies

**Comment by karlsso** [comment]
I'm not that experienced in programming. Is that easy to do?

**Comment by kalkih** [comment]
Seems like they had some bot detection in place, should be fixed now in [latest release](https://github.com/kalkih/passport-appointment-bot/releases/latest)

**Comment by robiot** [comment]
> Seems like they had some bot detection in place, should be fixed now in [latest release](https://github.com/kalkih/passport-appointment-bot/releases/latest)

Perfect
