### ISSUE TITLE
 [error]	Failed opening captcha page Cannot read properties of undefined (reading 'pages')

### ISSUE THREAD

**Issue by dio99** [kalkih/passport-appointment-bot#22]
{"level":"error","message":"Failed opening captcha page Cannot read properties of undefined (reading 'pages')","stack":"TypeError: Cannot read properties of undefined (reading 'pages')\n    at CaptchaService.openCaptcha (/snapshot/pass-bot/src/services/captchaService.js:75:35)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async CaptchaService.getNewVerifiedToken (/snapshot/pass-bot/src/services/captchaService.js:96:5)\n    at async BookingService.init (/snapshot/pass-bot/src/services/bookingService.js:61:27)\n    at async init (/snapshot/pass-bot/src/index.js:67:3)\n    at async /snapshot/pass-bot/src/index.js:56:5","timestamp":"2022-04-03T17:49:16.180Z"}

**Comment by olapola85** [comment]
Getting the same one

**Comment by kalkih** [comment]
@dio99 @olapola85, Do you have Google Chrome installed?

**Comment by dio99** [comment]
> @dio99 @olapola85, Do you have Google Chrome installed?

yes got chrome installed

**Comment by olapola85** [comment]
> @dio99 @olapola85, Do you have Google Chrome installed?

Doh! Sorry, working for me now

<3

**Comment by dio99** [comment]
> > @dio99 @olapola85, Do you have Google Chrome installed?
> 
> Doh! Sorry, working for me now
> 
> <3

hmm strange for me to now i just started to check

**Comment by dio99** [comment]
what can cause this ?  found free times 

[10:59:20] [success]	Östersund (2022-04-04) 9 free time slots
[10:59:20] [verbose]	Selecting timeslot (2022-04-04 16:30:00)
[10:59:20] [error]	Something went wrong when trying to book timeslot
[10:59:20] [error]	
[10:59:20] [error]	Error
    at BookingService.selectSlot (/snapshot/pass-bot/src/services/bookingService.js:198:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async BookingService.bookSlot (/snapshot/pass-bot/src/services/bookingService.js:155:7)
    at async handleBooking (/snapshot/pass-bot/src/index.js:132:19)
    at async checkAvailableSlotsForLocation (/snapshot/pass-bot/src/index.js:98:9)
[10:59:20] [error]	Failed booking slot 2022-04-04 16:30:00

**Comment by dio99** [comment]
> what can cause this ? found free times
> 
> [10:59:20] [success] Östersund (2022-04-04) 9 free time slots [10:59:20] [verbose] Selecting timeslot (2022-04-04 16:30:00) [10:59:20] [error] Something went wrong when trying to book timeslot [10:59:20] [error] [10:59:20] [error] Error at BookingService.selectSlot (/snapshot/pass-bot/src/services/bookingService.js:198:21) at processTicksAndRejections (node:internal/process/task_queues:96:5) at async BookingService.bookSlot (/snapshot/pass-bot/src/services/bookingService.js:155:7) at async handleBooking (/snapshot/pass-bot/src/index.js:132:19) at async checkAvailableSlotsForLocation (/snapshot/pass-bot/src/index.js:98:9) [10:59:20] [error] Failed booking slot 2022-04-04 16:30:00

aha oki it was due to i did not saw the catptcha that popup for book it
