### ISSUE TITLE
for-manga-anrop

### ISSUE THREAD

**Issue by gusadammu** [kalkih/passport-appointment-bot#25]
i have hade this issue and solved it. see the solution in the comment bellow.

![image](https://user-images.githubusercontent.com/55554359/161457752-7e099210-c206-4bd1-8ad5-6d2df1b6a21b.png)
and when you refresh the page you got
![image](https://user-images.githubusercontent.com/55554359/161457797-e60fda28-39ca-4a58-a3b2-a9650e45f70d.png)

**Comment by gusadammu** [comment]
this solution is based on an older version.

**Comment by kalkih** [comment]
This is already implemented in newer versions
