### ISSUE TITLE
min_date is not not working

### ISSUE THREAD

**Issue by danwie** [kalkih/passport-appointment-bot#26]
I set min_date to tomorrow. Got appointment today.

**Comment by geekteq** [comment]
I think it's working as intended.. as per documentation: _Earliest date to search for appointment (**will search all days in the week of the specified date**)_

**Comment by danwie** [comment]
I see. My misstake.

**Comment by kalkih** [comment]
Yes there is certainly room for improventa in regards to the min and max date, currently it will include the whole week of these dates as stated in the documentation.
