### ISSUE TITLE
socket hang up

### ISSUE THREAD

**Issue by danwie** [kalkih/passport-appointment-bot#27]
Not sure if they changed anything. Suddenly I get "socket hang up". But if I enter the booking site manually it seems to work fine (although a litte slow). I've also tried different ip-addresses (VPN) but with the same result.

```
$ ./passport-appointment-bot-macos-x64 
[13:13:52] [info]	Validating configuration...
[13:13:52] [success]	Configuration is valid
[13:13:52] [info]	Validating configured region...
[13:13:52] [success]	Valid region Stockholm
[13:13:52] [info]	Validating configured locations...
[13:13:52] [success]	Valid locations Järva, Sollentuna, Solna, Sthlm City, Södra Roslagen
[13:13:52] [info]	Starting booking session...
[13:13:52] [verbose]	Started captcha webserver on port 51827

/snapshot/pass-bot/node_modules/node-fetch/lib/index.js:1491
			reject(new FetchError(`request to ${request.url} failed, reason: ${err.message}`, 'system', err));
			       ^
FetchError: request to https://bokapass.nemoq.se/Booking/Booking/Index/stockholm failed, reason: socket hang up
    at ClientRequest.<anonymous> (/snapshot/pass-bot/node_modules/node-fetch/lib/index.js:1491:11)
    at ClientRequest.emit (node:events:390:28)
    at TLSSocket.socketOnEnd (node:_http_client:471:9)
    at TLSSocket.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET'
}

```

**Comment by dio99** [comment]
> Not sure if they changed anything. Suddenly I get "socket hang up". But if I enter the booking site manually it seems to work fine (although a litte slow). I've also tried different ip-addresses (VPN) but with the same result.
> 
> ```
> $ ./passport-appointment-bot-macos-x64 
> [13:13:52] [info]	Validating configuration...
> [13:13:52] [success]	Configuration is valid
> [13:13:52] [info]	Validating configured region...
> [13:13:52] [success]	Valid region Stockholm
> [13:13:52] [info]	Validating configured locations...
> [13:13:52] [success]	Valid locations Järva, Sollentuna, Solna, Sthlm City, Södra Roslagen
> [13:13:52] [info]	Starting booking session...
> [13:13:52] [verbose]	Started captcha webserver on port 51827
> 
> /snapshot/pass-bot/node_modules/node-fetch/lib/index.js:1491
> 			reject(new FetchError(`request to ${request.url} failed, reason: ${err.message}`, 'system', err));
> 			       ^
> FetchError: request to https://bokapass.nemoq.se/Booking/Booking/Index/stockholm failed, reason: socket hang up
>     at ClientRequest.<anonymous> (/snapshot/pass-bot/node_modules/node-fetch/lib/index.js:1491:11)
>     at ClientRequest.emit (node:events:390:28)
>     at TLSSocket.socketOnEnd (node:_http_client:471:9)
>     at TLSSocket.emit (node:events:402:35)
>     at endReadableNT (node:internal/streams/readable:1343:12)
>     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
>   type: 'system',
>   errno: 'ECONNRESET',
>   code: 'ECONNRESET'
> }
> ```
same issue for me now with that

**Comment by MartinHage** [comment]
I am also having the same issue. The bot worked fine until around 2022-04-04 12:30 CET but after a restart I started getting this error.

**Comment by xxandeer** [comment]
I did try it now and I also getting socket hang up at ClientRequest.

**Comment by skajagpangadig** [comment]
Tried it aswell and same error. Hopefully it will be patched soon so people wont need to queue at arlanda at 3am XD

**Comment by moyomo77** [comment]
Itś TLS problem, they don't support anymore "Cipher Suite: TLS_AES_256_GCM_SHA384 (0x1302)" or any off Cipher Suites (59 suites). Packet on: Server Hello, Change Cipher Spec, they choose: "Cipher Suite: TLS_AES_128_GCM_SHA256 (0x1301)" which passport-appointment-bot doesn't have on tls handshake. Hoppe somone could solve this. :D

**Comment by dio99** [comment]
> Works for me when if I patch the fetch function and change the user agent:
> 
> Change:
> 
> https://github.com/kalkih/passport-appointment-bot/blob/9e61b6e5e16262af94b8a7e19a121de4455e928a/src/services/bookingService.js#L35
> 
> To:
> 
> ```js
>     this._fetch = fetchCookie(nodeFetch)
>     this.fetch = async function(url, options) {
>       options = options || {}
>       let headers = {
>           "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4844.52 Safari/537.36"
>       }
>       Object.assign(headers, options.headers || {})
>       options.headers = headers
>       return this._fetch(url, options)
>     };
> ```

nice but i have some dep when try to build from src :(

rc $ cd ..
 ~/passport-appointment-bot $ npm install
npm WARN passport-appointment-bot@3.3.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
