### ISSUE TITLE
The beginner of beginners - so humble, but sooooo desperate

### ISSUE THREAD

**Issue by umanonearth** [kalkih/passport-appointment-bot#3]
Hello,
sorry for disturbing and for asking, I know my way around a computer a bit, but know nothing about programming but I am desperate for finding a time for passport... I have done as instructed but my computer wont run "passport-appointment-bot" tried run as administrator and "kör ändå" and so on... still get a small blue screen with the text "det går inte att köra den här appen på den här datorn" and "se om du kan hitta en version för den här datorn hos programvaruutgivaren". Jag har en WIndows 10 Pro, 64 bitars (Enhetsnamn	ITLTW10-2106A, Processor	11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz   2.80 GHz
Installerat RAM-minne	16,0 GB (15,6 GB går att använda)
Enhets-ID	01C43306-8FFD-4DCC-8075-6CF739D77374
Produkt-ID	00330-53256-57253-AAOEM
Systemtyp	64-bitars operativsystem, x64-baserad processor
Penna och pekskärm	Penn- eller tryckinmatning är inte tillgängligt för den här bildskärmen)

THought I give the option "Run from source a try" but do not know how to do the first step... 
"1.Clone the project, install dependencies with npm install"
becuause I lack the knowledge...

Is there any possibility you can help me?
The "how to" you have written is probably perfect for someone who knows programming but for me its just not enough.
Maybe just a little more information and if possible - with links to where I can find a good easy way to install what I need.

Hope for the best
Skulle vara oerhört tacksam för hjälp med detta!
//Tobias

**Comment by kalkih** [comment]
@umanonearth I've not tried running the precompiled .exe myself so might be an issue with it. I've tried the macos executable and it runs as expected.

As @xxandeer says, best bet would be to try running the program directly from the source instead, see instructions https://github.com/kalkih/passport-appointment-bot#run-from-source instructions.

**Comment by xxandeer** [comment]
I actually tried to run the windows version but could not get it to run @ W10.
If a recall corectly it said something about compatibilityissues

**Comment by xxandeer** [comment]
@umanonearth I have a linux dist running farming times for friends and familiy.
If you want I can help you, my server running 24/7 until it finds you the time.

**Comment by kalkih** [comment]
So I only compiled for `arm64` architectures... 🤦🏼 

[New release](https://github.com/kalkih/passport-appointment-bot/releases/latest) with x64 versions for windows and other platforms.

Also tested it on a windows machine with success.
@umanonearth Please give it another shot!

**Comment by umanonearth** [comment]
Thanks a million, will do!
