### ISSUE TITLE
Fail to open multiple Captchas

### ISSUE THREAD

**Issue by Nicozy** [kalkih/passport-appointment-bot#36]
I am unable to run multiple sessions as only the first captcha page opens up on chrome, the second one manages to open up chrome but tab stays blank and does not attempt to (visually atleast) to connect to the captcha website. I can run multiple clients thru cmd but anything more than 1 at a time messes up the next captcha. 
Attached a pic of how it looks: https://i.imgur.com/DthXPCj.png

Just figured id post here incase there is others with the same issue or an easy fix available.

**Comment by kalkih** [comment]
I believe it could be a timing issue, never been able to reproduce the issue myself.
Latest version has some changes made to the captcha page, hopefully fixed this, feel free to open another issue otherwise.
