### ISSUE TITLE
Bot not searching all dates.

### ISSUE THREAD

**Issue by tictactoes** [kalkih/passport-appointment-bot#37]
I've set a max date two weeks in the future but looking at the activity it seems to only search three individual dates within the range. Maybe I'm just misreading the log?

**Comment by kalkih** [comment]
The bot searches week by week, so when it says e.g. `2022-04-11`, it searches that whole week from Monday the 11th to Sunday the 17th.
Could probably improve the logging to make this clearer 👍🏼

**Comment by tictactoes** [comment]
Got it, thanks!
