### ISSUE TITLE
Fails to start booking session: ETIMEDOUT

### ISSUE THREAD

**Issue by skajagpangadig** [kalkih/passport-appointment-bot#38]
![b16c4cdef2cbe6a1d88b83a897e75b91](https://user-images.githubusercontent.com/102413213/162913279-9689cc4d-aa5d-4b26-a7b9-a73a2915e62d.png)

pulled a fresh install and got this error

**Comment by xxandeer** [comment]
Can you reach the booking site in a browser?

**Comment by kalkih** [comment]
What @xxandeer said, temporarily IP banned?
The error could be handled and presented nicer though... 😉

**Comment by 2high2die** [comment]
Same error for me. Can't get on browser via PC or mobile aswell.
Is it a temporary IP ban or is the site down? I haven't been on today and i got an error from start this morning... i didn't last night.

**Comment by kalkih** [comment]
Most likely a temporary IP ban then.
Permanently banning IP-addresses is a problematic method so I don't think they would go there, but you never know... 😉

**Comment by xxandeer** [comment]
actually one of my VPS was permabanned.
