### ISSUE TITLE
Implementation of BANK-ID signature

### ISSUE THREAD

**Issue by xxandeer** [kalkih/passport-appointment-bot#39]
This is not an issus as yet, but it has been announced that the BANK-ID signature implementation will be added tonight 22.00 UTC +2

**Comment by kalkih** [comment]
I probably won't have time to fix this until later this week.
If anyone wanna give it a shot before then, please do.

**Comment by xxandeer** [comment]
I have an solution but do not have the knowledge to fix this. But I can share my solution.

**Comment by kalkih** [comment]
The latest version of the bot now supports the new BankID identification step.
More to come.
