### ISSUE TITLE
booking_number

### ISSUE THREAD

**Issue by shsh1801** [kalkih/passport-appointment-bot#40]
Hi, im trying to test with booking_number but its not working for me... maybe I'm adding it wrong in config file, how should it be added?

**Comment by xxandeer** [comment]
”Ombokning” is brokend from tonight since Polismyndigheten added bankid even for ombokning.

**Comment by kalkih** [comment]
Unfortunate, but it was really bound to happen sooner or later.
Added support for the BankID step in the latest release when providing an existing booking number as well.
