### ISSUE TITLE
Cannot read properties of undefined (reading 'text')

### ISSUE THREAD

**Issue by MarcusOtter** [kalkih/passport-appointment-bot#7]
Hello! Thanks for making this project, it looks very promising 👍 

I am running the v2.2.0 `.exe` file on a Windows machine. It had been running for maybe an hour at most, but then I got this error: `Cannot read properties of undefined (reading 'text')`

After restarting it, it's running very slow. Before it was checking about 2.5 weeks/second, now it's down to as low as 0.05. I double checked my internet connection but it remains stable at what I had before getting this error, so it shouldn't be a problem on my end.

![image](https://user-images.githubusercontent.com/35617441/160708970-d25cc615-e989-4b89-8b2d-7a94068e9390.png)

I included my config and the error log below.

`config.json`
```json
{
  "region": "Uppsala",
  "locations": ["Enköping", "Tierp", "Uppsala", "Östhammar"],
  "max_date": "2022-07-30",
  "email": "redacted@example.com",
  "phone": "0123123123",
  "firstname": ["Redacted", "Redacted", "Redacted", "Redacted", "Redacted"],
  "lastname": ["Redacted", "Redacted", "Redacted", "Redacted", "Redacted"],
  "passport": true,
  "id": false,
  "sessions": 1,
  "throttle": 0
}
```

`.error.log`
```json
{"level":"error","message":"request to https://bokapass.nemoq.se/Booking/Booking/Next/uppsala failed, reason: read ECONNRESET","timestamp":"2022-03-29T21:08:54.513Z"}
{"level":"error","message":"Cannot read properties of undefined (reading 'text')","timestamp":"2022-03-29T21:08:54.515Z"}
{"level":"error","message":"request to https://bokapass.nemoq.se/Booking/Booking/Next/uppsala failed, reason: read ECONNRESET","timestamp":"2022-03-29T21:09:09.872Z"}
```

**Comment by MarcusOtter** [comment]
Also the program seems to be getting in loops like this every now and then, not sure what that means exactly. Seems like it's not making any requests at all when this happens?
![image](https://user-images.githubusercontent.com/35617441/160709763-a409c3ba-ef42-4a4c-870a-3024c0aae8e6.png)

**Comment by MarcusOtter** [comment]
Now it's spinning back up. My guess is that this was a problem with nemoq.se latency? In that case I think it makes sense for this program to warn/skip when requests take longer than a couple seconds to complete! :)

**Comment by kalkih** [comment]
Hey,

The booking system has been very slow from time to time from my experience, so you are probably correct in your assessment there.
A warning to indicate that the system is slow is not a bad idea, I'll add something when I have time 👍🏼

**Comment by MarcusOtter** [comment]
For anyone else encountering this problem, a much more reliable setting for me was to put `sessions = 4` (matching the amount of locations I have) and `delay = 1`. This has kept it at 3 weeks / second for the last hour. Perhaps that would be a better default to give as well.

**Comment by skajagpangadig** [comment]
What does chaning the seassion do and I can't find the delay in config.json?

**Comment by MarcusOtter** [comment]
@skajagpangadig The documentation for the configuration options exists in [the README file](https://github.com/kalkih/passport-appointment-bot#configuration). And excuse my mistake, I meant `throttle = 1`, not `delay = 1`.
