### ISSUE TITLE
Booking for more than one person?

### ISSUE THREAD

**Issue by Steinmarkh** [kalkih/passport-appointment-bot#9]
Hi!

Is there a way for this script to make the choice of booking for more than one person?

I can add names in the config file, but that only adds several names to person 1 in a one person booking. It doesn't make a booking for each of the names added. 
![Starting](https://user-images.githubusercontent.com/102699203/160932680-88e27dfa-adc9-477b-a51f-54ff51fd63f1.jpg)

![Antal personer](https://user-images.githubusercontent.com/102699203/160932676-d5be4225-7f78-4b25-b226-1637368f3bc3.JPG)

**Comment by kalkih** [comment]
Hey,

Yes, up to 8 persons are supported, you need to specify both `firstname` and `lastname` in the config for each person.

config example

```yaml
  ...
  firstname: ["John", "Jane"],
  lastname: ["Doe", "Doe"]
  ...
```

**Comment by Steinmarkh** [comment]
I have added names in the way you describe. But that only makes a bokning for one person. However, the name of that one person will be ”John, Jane”. Not making a booking for two separate persons. :-)

![967FEEDE-75C9-469F-AC4A-688D137AA245](https://user-images.githubusercontent.com/102699203/160938986-909085c3-c2d3-4269-a441-20bd6b3a3c57.jpeg)

**Comment by kalkih** [comment]
Be careful with how you place the quotes, each name should be in quotes, see my example.

If you still have issues, please post your config.
